/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Vistas.Almacen.frmCategoriasAlmacen;
import Vistas.Almacen.frmInsumos;
import Vistas.Almacen.frmNuevoInsumo;
import Vistas.Compras.frmComprar;
import Vistas.Compras.frmProveedor;
import Vistas.Compras.frmVerCompras;
import Vistas.Productos.frmCategoriasProductos;
import Vistas.Productos.frmOferta;
import Vistas.Productos.frmProducto;
import Vistas.Productos.frmVerOfertas;
import Vistas.Productos.frmVerProductos;
import Vistas.Ventas.frmVentas;
import java.awt.Dimension;

/**
 *
 * @author Usuario
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public FrmPrincipal() {
        initComponents();
        setExtendedState(this.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorioPrincipal = new javax.swing.JDesktopPane();
        menuPrincipal = new javax.swing.JMenuBar();
        menuAlmacen = new javax.swing.JMenu();
        itemCategoriaAlmacen = new javax.swing.JMenuItem();
        itemInsumos = new javax.swing.JMenuItem();
        menuCompras = new javax.swing.JMenu();
        itemProveedor = new javax.swing.JMenuItem();
        itemComprar = new javax.swing.JMenuItem();
        itemVerCompras = new javax.swing.JMenuItem();
        menuProductos = new javax.swing.JMenu();
        itemCategoriaProducto = new javax.swing.JMenuItem();
        itemProducto = new javax.swing.JMenuItem();
        itemVerProductos = new javax.swing.JMenuItem();
        itemOferta = new javax.swing.JMenuItem();
        itemVerOfertas = new javax.swing.JMenuItem();
        menuVentas = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1024, 481));

        javax.swing.GroupLayout escritorioPrincipalLayout = new javax.swing.GroupLayout(escritorioPrincipal);
        escritorioPrincipal.setLayout(escritorioPrincipalLayout);
        escritorioPrincipalLayout.setHorizontalGroup(
            escritorioPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
        );
        escritorioPrincipalLayout.setVerticalGroup(
            escritorioPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        menuAlmacen.setText("Almacen");

        itemCategoriaAlmacen.setText("Categorías");
        itemCategoriaAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCategoriaAlmacenActionPerformed(evt);
            }
        });
        menuAlmacen.add(itemCategoriaAlmacen);

        itemInsumos.setText("Insumos");
        itemInsumos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemInsumosActionPerformed(evt);
            }
        });
        menuAlmacen.add(itemInsumos);

        menuPrincipal.add(menuAlmacen);

        menuCompras.setText("Compras");

        itemProveedor.setText("Proveedor");
        itemProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemProveedorActionPerformed(evt);
            }
        });
        menuCompras.add(itemProveedor);

        itemComprar.setText("Comprar");
        itemComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemComprarActionPerformed(evt);
            }
        });
        menuCompras.add(itemComprar);

        itemVerCompras.setText("Ver Compras");
        itemVerCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemVerComprasActionPerformed(evt);
            }
        });
        menuCompras.add(itemVerCompras);

        menuPrincipal.add(menuCompras);

        menuProductos.setText("Productos");

        itemCategoriaProducto.setText("Categorías");
        itemCategoriaProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCategoriaProductoActionPerformed(evt);
            }
        });
        menuProductos.add(itemCategoriaProducto);

        itemProducto.setText("Producto");
        itemProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemProductoActionPerformed(evt);
            }
        });
        menuProductos.add(itemProducto);

        itemVerProductos.setText("Ver Productos");
        itemVerProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemVerProductosActionPerformed(evt);
            }
        });
        menuProductos.add(itemVerProductos);

        itemOferta.setText("Oferta");
        itemOferta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemOfertaActionPerformed(evt);
            }
        });
        menuProductos.add(itemOferta);

        itemVerOfertas.setText("Ver Ofertas");
        itemVerOfertas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemVerOfertasActionPerformed(evt);
            }
        });
        menuProductos.add(itemVerOfertas);

        menuPrincipal.add(menuProductos);

        menuVentas.setText("Ventas");
        menuVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuVentasMouseClicked(evt);
            }
        });
        menuVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVentasActionPerformed(evt);
            }
        });
        menuPrincipal.add(menuVentas);

        setJMenuBar(menuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorioPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorioPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemVerComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemVerComprasActionPerformed
        frmVerCompras verCompras = new frmVerCompras();
        escritorioPrincipal.add(verCompras);
        Dimension desktopSize = escritorioPrincipal.getSize();
        Dimension FrameSize = verCompras.getSize();
        verCompras.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        verCompras.show();
    }//GEN-LAST:event_itemVerComprasActionPerformed

    private void itemProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemProductoActionPerformed
        frmProducto producto = new frmProducto();
        escritorioPrincipal.add(producto);
        Dimension desktopSize = escritorioPrincipal.getSize();
        Dimension FrameSize = producto.getSize();
        producto.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        producto.show();
    }//GEN-LAST:event_itemProductoActionPerformed

    private void itemCategoriaAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCategoriaAlmacenActionPerformed
        frmCategoriasAlmacen categoriasAlmacen = new frmCategoriasAlmacen();
        escritorioPrincipal.add(categoriasAlmacen);
        Dimension desktopSize = escritorioPrincipal.getSize();
        Dimension FrameSize = categoriasAlmacen.getSize();
        categoriasAlmacen.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        categoriasAlmacen.show();
    }//GEN-LAST:event_itemCategoriaAlmacenActionPerformed

    private void itemInsumosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemInsumosActionPerformed
        frmInsumos insumo = new frmInsumos();
        frmNuevoInsumo nuevoInsumo = new frmNuevoInsumo();
        escritorioPrincipal.add(insumo);
        escritorioPrincipal.add(nuevoInsumo);
        Dimension desktopSize = escritorioPrincipal.getSize();
        Dimension FrameSize = insumo.getSize();
        insumo.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        insumo.show();
    }//GEN-LAST:event_itemInsumosActionPerformed

    private void itemProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemProveedorActionPerformed
        frmProveedor proveedor = new frmProveedor();
        escritorioPrincipal.add(proveedor);
        Dimension desktopSize = escritorioPrincipal.getSize();
        Dimension FrameSize = proveedor.getSize();
        proveedor.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        proveedor.show();
    }//GEN-LAST:event_itemProveedorActionPerformed

    private void itemComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemComprarActionPerformed
        frmComprar comprar = new frmComprar();
        escritorioPrincipal.add(comprar);   
        Dimension desktopSize = escritorioPrincipal.getSize();
        Dimension FrameSize = comprar.getSize();
        comprar.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        comprar.show();
    }//GEN-LAST:event_itemComprarActionPerformed

    private void itemCategoriaProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCategoriaProductoActionPerformed
        frmCategoriasProductos categoriaProducto = new frmCategoriasProductos();
        escritorioPrincipal.add(categoriaProducto);
        Dimension desktopSize = escritorioPrincipal.getSize();
        Dimension FrameSize = categoriaProducto.getSize();
        categoriaProducto.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        categoriaProducto.show();
    }//GEN-LAST:event_itemCategoriaProductoActionPerformed

    private void itemVerProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemVerProductosActionPerformed
        frmVerProductos verProductos = new frmVerProductos();
        escritorioPrincipal.add(verProductos);
        Dimension desktopSize = escritorioPrincipal.getSize();
        Dimension FrameSize = verProductos.getSize();
        verProductos.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        verProductos.show();
        
    }//GEN-LAST:event_itemVerProductosActionPerformed

    private void itemOfertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemOfertaActionPerformed
        frmOferta oferta = new frmOferta();
        escritorioPrincipal.add(oferta);
        Dimension desktopSize = escritorioPrincipal.getSize();
        Dimension FrameSize = oferta.getSize();
        oferta.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        oferta.show();
    }//GEN-LAST:event_itemOfertaActionPerformed

    private void itemVerOfertasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemVerOfertasActionPerformed
        frmVerOfertas verOferta = new frmVerOfertas();
        escritorioPrincipal.add(verOferta);
        Dimension desktopSize = escritorioPrincipal.getSize();
        Dimension FrameSize = verOferta.getSize();
        verOferta.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        verOferta.show();
    }//GEN-LAST:event_itemVerOfertasActionPerformed

    private void menuVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVentasActionPerformed
        
    }//GEN-LAST:event_menuVentasActionPerformed

    private void menuVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuVentasMouseClicked
        frmVentas ventas = new frmVentas();
        escritorioPrincipal.add(ventas);
        Dimension desktopSize = escritorioPrincipal.getSize();
        Dimension FrameSize = ventas.getSize();
        ventas.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        ventas.show();
    }//GEN-LAST:event_menuVentasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane escritorioPrincipal;
    private javax.swing.JMenuItem itemCategoriaAlmacen;
    private javax.swing.JMenuItem itemCategoriaProducto;
    private javax.swing.JMenuItem itemComprar;
    private javax.swing.JMenuItem itemInsumos;
    private javax.swing.JMenuItem itemOferta;
    private javax.swing.JMenuItem itemProducto;
    private javax.swing.JMenuItem itemProveedor;
    private javax.swing.JMenuItem itemVerCompras;
    private javax.swing.JMenuItem itemVerOfertas;
    private javax.swing.JMenuItem itemVerProductos;
    private javax.swing.JMenu menuAlmacen;
    private javax.swing.JMenu menuCompras;
    private javax.swing.JMenuBar menuPrincipal;
    private javax.swing.JMenu menuProductos;
    private javax.swing.JMenu menuVentas;
    // End of variables declaration//GEN-END:variables
}
